services:
  web:
    build:
      context: ./eng_ex_gen
      dockerfile: Dockerfile
    container_name: engexgen
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./eng_ex_gen/.env
    volumes:
      - sqlite_data:/app/db
      - gensim_data:/root/gensim-data

volumes:
  sqlite_data:
  gensim_data:
