services:
  web:
    build:
      context: ./eng_ex_gen
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./eng_ex_gen/.env
    volumes:
      - sqlite_data:/app/db

volumes:
  sqlite_data:
