# Generated by Django 4.2.3 on 2023-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='answer',
            field=models.CharField(blank=True, default='Default', max_length=1000),
        ),
    ]
