# Generated by Django 5.0.3 on 2026-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_alter_sentences_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentences",
            name="session_key",
            field=models.CharField(db_index=True, default="", max_length=40),
        ),
    ]
